@startuml

:new Actor:--(Identificarse)
:new Actor:--(Pagar)
:new Actor:--(Elegir mensajero)
:new Actor:--(Confirmar)
(Identificarse)<--(Registrarse):<<extend>>
(Pagar)<|--(Pagar con tarjeta)
(Pagar)<|--(Pagar con transferencia)


@enduml