@startuml

:Cliente:--(Meter dinero)
:Cliente:--(Pedir azucar)
:Cliente:--(Pedir producto)
:Cliente:--(Cancelar)
(Pedir producto)-.>(Devolver dinero):<<include>>
(Cancelar)-.>(Devolver dinero):<<include>>

@enduml